# Site Settings
name: kuturana
title: /kuturana
email: nizar@mailbox.org
description:
baseurl: ''
url: 'http:kuturana.github.io'
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
excerpt_separator: <!--more-->
plugins: [jekyll-paginate]
paginate: 6
paginate_path: /page:num/
